
= Hyperparameter Optimization: Getting the Most Out of Your Models
Justin M. Wozniak <wozniak@mcs.anl.gov>

== Installation

=== Install R

----
wget
./configure --prefix=$HOME/R-3.4.3 --without-ICU
make -j 4
make install
----

=== Install EQ/R

----
$ cd EQ-R/eqr
$ cp settings.template.sh settings.sh
# edit settings.sh to set R_HOME, Tcl settings
$ source settings.sh
$ ./configure --prefix=$PWD/..
$ make -j 2
$ make install
----

=== Install Swift/T

First, install MPICH:
----
$ sudo apt-get install mpich
----

Or install from source:

----
$ wget http://www.mpich.org/static/downloads/3.2.1/mpich-3.2.1.tar.gz
$ tar xfz mpich-3.2.1.tar.gz
$ ./configure --prefix=...
$ make -j 4
$ make install
----

Install Swift/T using the release package here:

* http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
* http://swift-lang.github.io/swift-t/downloads.html

----
$ wget http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
$ tar xfz swift-t-1.3.tar.gz
$ cd swift-t-1.3
$ dev/build/init-settings.sh
----

Then, edit dev/build/swift-t-settings.sh .
. Set SWIFT_T_PREFIX to any desired installation location
. Set ENABLE_R=1
. Set R_INSTALL to your R installation

Then:

----
$ dev/build/build-all.sh
----

If the build is successful, you will see a final message BUILD SUCCESSFUL from Ant.

Then, add the reported stc/bin directory to your PATH.  This contains the executable program *swift-t* .

You can test the Swift/T installation by running:

----
$ swift-t -E 'trace(42);'
trace: 42
----

== Install the Benchmark

This is a cancer benchmark.

=== Get the source code

----
$ git clone https://github.com/ECP-CANDLE/Benchmarks.git
$ cd Benchmarks
$ git checkout frameworks
----

Note where the Benchmarks are installed

----
BENCHMARKS=$PWD
----

== Test the benchmark

Run this to test the benchmark by itself (no hyperparameter search), and look for the given output.

----
$ cd $BENCHMARKS/Pilot1/NT3
# Check you are using the right python executable, then:
$ python nt3_baseline_keras2.py
Using TensorFlow backend.
...
Params: { ...
----

== Run the optimization workflow

. Edit model.sh to set PYTHONPATH to your Benchmarks location
. Edit workflow.sh to set the R variable to your R installation

Then, run:

----
$ cd Topics/5_hyperparam_opt
$ ./workflow.sh X01
----

== Systems with MPICH and OpenMPI

This may result in conflicts.  After installing MPICH, do:

----
$ sudo update-alternatives --set mpi /usr/include/mpich
----

Then, in swift-t-settings.sh set:

----
MPI_LIB_DIR=/usr/lib/mpich/lib
----

and in dev/build/turbine-build.sh, set:

----
EXTRA_ARGS=--with-launcher=/usr/bin/mpiexec.mpich
----
