
= Hyperparameter Optimization: Getting the Most Out of Your Models
Justin M. Wozniak <wozniak@mcs.anl.gov>

== Installation

=== Install Hyperopt

----
$ pip install hyperopt
----

=== Install Swift/T

First, install MPICH:
----
$ sudo apt-get install mpich
----

Install Swift/T using the release package here:

* http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
* http://swift-lang.github.io/swift-t/downloads.html

----
$ wget http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
$ tar xfz swift-t-1.3.tar.gz
$ cd swift-t-1.3
$ dev/build/init-settings.sh
----

Then, edit dev/build/swift-t-settings.sh .
. Set SWIFT_T_PREFIX to any desired installation location
. Either
.. Uncomment ENABLE_PYTHON=1 and ensure the correct python executable is in PATH, or
.. Set PYTHON_EXE to your Anaconda Python executable (typically $HOME/anaconda3/bin/python)

Then:

----
$ dev/build/build-all.sh
----

If the build is successful, you will see a final message BUILD SUCCESSFUL from Ant.

Then, add the reported stc/bin directory to your PATH.  This contains the executable program *swift-t* .

== Run the optimization workflow

----
$ cd Topics/5_hyperparam_opt
$ ./workflow.sh X01
----



== Systems with MPICH and OpenMPI

This may result in conflicts.  After installing MPICH, do:

----
$ sudo update-alternatives --set mpi /usr/include/mpich
----

Then, in swift-t-settings.sh set:

----
MPI_LIB_DIR=/usr/lib/mpich/lib
----

and in dev/build/turbine-build.sh, set:

----
EXTRA_ARGS=--with-launcher=/usr/bin/mpiexec.mpich
----
