
= Hyperparameter Optimization: Getting the Most Out of Your Models
Justin M. Wozniak <wozniak@mcs.anl.gov>

== Installation

=== Install R

----
wget
./configure --without-ICU
make -j 4
make install
----

=== Install EQ/R

----
cd EQ-R/eqr
R=$HOME/Public/sfw/R-3.4.3/lib/R
export CPPFLAGS="-I/usr/include/tcl8.6
   -I$R/include
   -I$R/library/Rcpp/include
   -I$R/library/RInside/include"

export LDFLAGS="-L/usr/lib/tcl8.6 -L$R/lib -L$R/library/Rcpp/lib -L$R/library/RInside/lib"

./configure --prefix=$PWD/.. \
  
make -j 2
make install
----

=== Install Swift/T

First, install MPICH:
----
$ sudo apt-get install mpich
----

Install Swift/T using the release package here:

* http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
* http://swift-lang.github.io/swift-t/downloads.html

----
$ wget http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-1.3.tar.gz
$ tar xfz swift-t-1.3.tar.gz
$ cd swift-t-1.3
$ dev/build/init-settings.sh
----

Then, edit dev/build/swift-t-settings.sh .
. Set SWIFT_T_PREFIX to any desired installation location
. Either
.. Uncomment ENABLE_PYTHON=1 and ensure the correct python executable is in PATH, or
.. Set PYTHON_EXE to your Anaconda Python executable (typically $HOME/anaconda3/bin/python)

Then:

----
$ dev/build/build-all.sh
----

If the build is successful, you will see a final message BUILD SUCCESSFUL from Ant.

Then, add the reported stc/bin directory to your PATH.  This contains the executable program *swift-t* .

You can test the Swift/T installation by running:

----
$ swift-t -E 'trace(42);'
trace: 42
----

== Install the Benchmark

This is a cancer benchmark.

=== Get the source code

----
$ git clone https://github.com/ECP-CANDLE/Benchmarks.git
$ cd Benchmarks
$ git checkout frameworks
----

Note where the Benchmarks are installed

----
BENCHMARKS=$PWD
----

=== Get the data

Run the data downloader script from the Tutorial clone and the BENCHMARKS location noted above.

----
$ Topics/5_hyperparam_opt/get-data.sh $BENCHMARKS
----

== Test the benchmark

Run this to test the benchmark by itself (no hyperparameter search), and look for the given output.

----
$ cd $BENCHMARKS/Pilot1/Combo
# Check you are using the right python executable, then:
$ python combo_baseline_keras2.py
Using TensorFlow backend.
...
Params: {'activation': 'relu' ...
----

== Run the optimization workflow

----
$ cd Topics/5_hyperparam_opt
$ ./workflow.sh X01
----



== Systems with MPICH and OpenMPI

This may result in conflicts.  After installing MPICH, do:

----
$ sudo update-alternatives --set mpi /usr/include/mpich
----

Then, in swift-t-settings.sh set:

----
MPI_LIB_DIR=/usr/lib/mpich/lib
----

and in dev/build/turbine-build.sh, set:

----
EXTRA_ARGS=--with-launcher=/usr/bin/mpiexec.mpich
----
